project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
      - doc
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望 chat list 提供一个刷新按钮，可以刷新agentLoader，重新加载agentConfig，并清空所有缓存的agent，同时重新加载所有的chat。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup