project:
  base_path: ./
  ignore:
    path:
      - target
      - "*/.idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望重试的时候，会删掉的不只是最后一个Bot消息，而是最后一个User消息之后的全部的Bot消息。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup