project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望 MessageHandler 添加一个handleTask函数，message只是一种特殊的task，handleMessage会直接调用handleTask，这样可以减少重复代码。
    task要在ai-agent-response中实现。通过jsdoc标明现在的task都有哪些属性。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup