project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/webview/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
      - doc
      - README.md
      # - job
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    ## 任务约束
    
    - 分清webview的代码和插件的代码和agent app的代码

    ## 任务

    我希望 thread创建的时候，创建一个knowledge_space的文件夹和对应的json文件，里面存储的是knowledge_space的数据。
    ```
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup