project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
      - doc
      - README.md
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    ## 任务约束
    
    - 无

    ## 任务

    我希望 点击edit按钮进行编辑的时候，初始编辑框的宽度是chat-box的宽度的80%
    
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup