project:
  base_path: ./
  ignore:
    path:
      - target
      - "*/.idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    目前这个发了消息之后，当返回的是stream的response的时候，html上不会流式展示，非要等所有的都输出完才一次更新，请修正这个bug。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup