project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
      - doc
      - README.md
      - job
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    ## 任务约束
    
    - 分清webview的代码和插件的代码和agent app的代码
    - 我希望每个agent app有一个自己package.json文件，这样可以单独安装依赖
    - agents.json的参考结构如下：
    ```
    {
      "agents": [
        {
            "name": "testAgent",
            "path": "./example/TestAgent.js",
            "metadata": {}
        }
      ]
    }
    - 

    ## 任务

    我希望 agent marketplace的安装位置是当前目录下的ai_helper/prompt_builder/agent，而不是插件位置。
    ```
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup