project:
  base_path: ./
  ignore:
    path:
      - target
      - "*/.idea"
      - .mvn
      - node_modules
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - repo_to_git.yml
      - media
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望点击send-btn或在user-input敲回车是可以更新消息列表的，但是目前会报错。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup