project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望，botResponseComplete的时候，遍历所有的消息，给每个加一个edit按钮，点击之后可以编辑这个消息，并保存到thread文件里。
    但是目前的实现由bug，第一次点击edit按钮的时候save和cancel按钮不显示，导致无法保存或取消。
    请修复这个bug。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup