project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望 没有 ai_helper/agent/agents.json 文件，报错的时候要弹出提示。而不是直接抛出异常。
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup