project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    我希望 chat-view的message 的edit按钮的前面增加一个copy按钮，点击后可以复制message的origin内容到剪贴板
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup