project:
  base_path: ./
  filters:
    - ignore:
      - target
      - ".idea"
      - .mvn
      - node_modules/@(.*)
      - node_modules/!(ai-agent-response)
      - ai_helper
      - "**/spike"
      - ".git"
      - "*/node_modules"
      - config.yml
      - "**/*.png"
      - "**/.DS_Store"
      - "**/LICENSE.txt"
      - "**/package-lock.json"
      - media
      - "*/test"
      - "*.log"
      - "chat/lib"
      - "*.yml"
      - "**/*.vsix"
      - dist
      - temp
      - doc
      - README.md
input:
  git_clone_to_path: ai_helper/prompt_builder/git_repo
  instruction: |
    ## 任务约束
    
    - 修改webview的时候，js只能写在script.js里。不允许写在html里。
    - 如果其他文件不需要修改，就不要生成了。

    ## 任务
    我希望 chat-view.html 里，message 如果 isHTML为true的话，那么直接使用text，否则才renderMarkdown。
    你要考虑有哪些地方都渲染了Markdown，都要注意。
    
  skip_clone_if_folder_exist: true  
output:     
  prompt:
    path: ai_helper/prompt_builder/output/working
    backup_path: ai_helper/prompt_builder/output/backup